server:
  port: 19091

spring:
  application:
    name: user-service

  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      fail-fast: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379


  flyway:
    schemas: user_schema
    create-schemas: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  # 로컬 DB 연결
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

# 키클락 설정
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: sanjijk
  client-id: user-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

admin :
  manager-key : ${MANAGER_KEY}
  master-key : ${MASTER_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, circuitbreakers
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      keycloak:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  timelimiter:
    instances:
      keycloak:
        timeoutDuration: 3s
