{
 "title": "Spring Boot Observability",
 "tags": [
  "spring-boot",
  "sanji"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Keyword" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"}) / sum by(uri)(http_server_requests_seconds_count{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=~\"$app_name\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=~\"$app_name\", status=~\"2.*\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"}) / sum by(uri) (http_server_requests_seconds_count{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=~\"$app_name\", status=~\"5.*\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"}) / sum by(uri) (http_server_requests_seconds_count{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(http_server_requests_seconds_bucket{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "P95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(http_server_requests_seconds_bucket{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=~\"$app_name\", uri!=\"/actuator/prometheus\", uri!~\".*profiles:.*\", uri!=\"UNKNOWN\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Log Level Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(level) (rate({service=~\"$app_name\"} | json | level != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{service=~\"$app_name\"} | json |= \"$log_keyword\""
    }
   ]
  }
 ]
}