server:
  port: 19097

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:postgres}?currentSchema=ai_schema
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ai_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-1.5-flash
      embedding:
        options:
          model: text-embedding-004
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768

ai:
  chat:
    session-expire-hours: 24
    similarity-threshold: 0.7
    top-k: 3
