server:
  port: 8000

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**, /api/auth/**
            - id: auction-service
              uri: lb://auction-service
              predicates:
                - Path=/api/auctions/**, /api/products/**
            - id: bid-service
              uri: lb://bid-service
              predicates:
                - Path=/api/bids/**
            - id: bid-service-ws
              uri: lb:ws://bid-service
              predicates:
                - Path=/ws/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**
            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/api/ai/**
