server:
  port: 19094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:postgres}?currentSchema=order_schema
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: order_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
