server:
  port: 19091

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379
  jpa:
    open-in-view: false # DB 커넥션이 Keycloak HTTP 호출 중에도 점유되는 것을 방지
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
